Example template compile fix
Template can't be compiled because of `TS7030`.

```
 error TS7030: Not all code paths return a value.
```

Fixed by adding dummy return.